--- #YAML:1.0
name:                XML-Twig
version:             3.28
abstract:            XML, The Perl Way
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    XML::Parser:                   2.23
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Michel Rodriguez <mirod@xmltwig.com>
